### ISSUE TITLE
Task timing out

### ISSUE THREAD

**Issue by agbodi** [opsta/ansible-nexus#13]
- name: Wait until initial admin password is appear
  register: nexus_is_find_init_token
  wait_for:
    timeout: 60
    path: "{{ nexus_admin_init_password_path }}"

The task above is constantly timing out because the admin.password file is never created

**Comment by winggundamth** [comment]
@agbodi I put fixed along with my latest PR here https://github.com/opsta/ansible-nexus/pull/12

**Comment by winggundamth** [comment]
@agbodi It should fixed. Please test.

**Comment by agbodi** [comment]
I fixed it on my end by increasing the timeout value from 60. Depending on the infrastructure one is running it on, it sometimes takes more than 60 seconds for admin.password to get generated.
